import { createSlice } from "@reduxjs/toolkit";

// initial state for the data slice
const initialState = {
  fetchedData: null,
};

export const dataSlice = createSlice({
  name: "data", // the name of the slice
  initialState,
  reducers: {
    // reducer function to set the fetched data
    setData: (state, action) => {
      state.fetchedData = action.payload; // setting the fetched data to the state with the payload provided
    },
  },
});

export const { setData } = dataSlice.actions;

// exporting reducer function generated by createSlice
export default dataSlice.reducer;
